### PR TITLE
Addition of More Roleplay Commands

### PR DESCRIPTION
**Pull request by BearTS**
Gif Addition is still left but i will do it

### CODE REVIEW

**Comment by maisans-maid** [comment]
Possible duplicate of #81

**Comment by BearTS** [comment]
Can Merge Now 👍

**Comment by buttermiilk** [comment]
@BearTS, duplicate object key at line 31 and line 170, images.json.

Possible fix:
```json
{
  "baka":[
    "AdFWT3q", "WUWKIfd", "jFSnFit", "Wfw5QHh", "nHAl4Qt", "idyYLuA",
    "RqBL21C", "M30Q4qa", "84etIl2", "QE5ETrU", "xFkJfSP", "4hyZ7lp",
    "TG1ygR1", "vXNI2aI", "uTRZcus", "pc4lJy9", "srw0v17", "fRN8t33",
    "tSGDGRS", "8ndgFuN", "r8rEQgH", "ZyaJNIV", "1CGujwz", "kWRnK3F",
    "3eSRCmQ", "I2kj8mC"
  ],
  "blush":[
    "fuPUm5L", "fQHHRJR", "PY8s03Q", "2vJG2Hz", "UT4TBVk", "WnbizWJ",
    "t2lhJYR", "lTxGOsH", "ddD5hD7", "yLJREfa", "hzTHUIM", "sjTvKDp",
    "e6Ve76r", "IROuDCJ", "paOfyGh", "YS3wBa0", "Hyw1iKi", "CB9dMFU"
  ],
  "cry":[
    "B1REi0W", "hAdb8CE", "K1rabup", "akTsUty", "BOOM0Os", "LUvKlUa",
    "4sUlQ3f", "uaYKEOO", "I9SR8SS", "Ug74IEz", "1RtCcIx", "s7qnBiL",
    "vGZXzny", "YxlmCQA", "nKHb7eZ", "srzVufj", "CEYnvBs", "0ObMKAa",
    "uu9kLPA", "Un6E49N", "qP2Qbrt", "a6Y8DL7", "LjvGzlu", "HlEdnSJ",
    "uO2D3aM", "AxzRI4S", "u7TDFoW", "8zPXo20", "Jgon81m", "F7mgXxA",
    "lmhnsP1", "4tKvQB4", "q72jKeC", "Yy7kY9p", "64Wb7ih", "ZTVUGUK",
    "LpVia9q", "aTVh8Fi", "UAD8ipb", "TUpr1xD", "pXvW00A", "bCVLo6C",
    "KQ6tbMO", "AHjTnRH", "OpHWgrl", "WOePFco", "bT3oYX8", "4IlqpPP",
    "FhKy590", "6tyPGCE", "OIsGiMI", "tO8w6HC", "n00lcUf", "Mp7sULU",
    "Jvx7aaF", "1mZoi4G", "WZfGLMG", "iCH3QZ5", "aIFULcR", "lLZF4X0",
    "OpLCddD", "nFb4jL4", "f9CvzVc", "prk2765", "iBJq5gc", "cEVDoUf",
    "zC2hyjT", "76KuRKg", "6lN1Kju", "ZqAv3fp", "ENHgYAG", "yGOTAls",
    "RAsJIMe", "67TineD", "kI05If7", "RR3CP44", "LJ5ihzn", "MMBtlgH",
    "Zk3Hiw8", "CLzFBlA", "0ReTRnH", "Jjdcs6B", "YPVFNMR"
  ],
  "cringe":[],
  "dance": [
    "sZ750iM", "yFE0A4z", "cjcYrqI","28zzdho","5ULGhAn","hgOoVQT",
    "YbdJb5Z", "VV8f9TC","P3pdnij", "sZ750iM", "yFE0A4z", "cjcYrqI","28zzdho","5ULGhAn","hgOoVQT",
    "YbdJb5Z", "VV8f9TC","P3pdnij"
  ],
  "disgust":[
    "QWnfJAH", "SBfI0G6", "njSUTVF", "YTzm1sN", "fWj0VTx", "zy5fUCK",
    "baKjBxC", "bgP3kXO", "DXburdT", "MuS9YpB", "mKuXemO", "QIUuzBq",
    "X4e6T4L", "N9uBZuE", "ud1kqo7", "yzMDT3g", "5xQJ6dH", "vFE6dnx",
    "pyxLdyR", "93FFsdY", "8xC8POE", "0PiqIwV", "LvyXnNV", "5u6BKEc",
    "kR8t7rq"
  ],
  "feed": [
    "naPItDn", "kGWmok2", "NlwR3on", "h7Q2qmN", "PdFT12Q", "22iZkA2",
    "UkJdJPq", "Cocgdkl", "iZYMQVg", "9iEk6dL", "qMIT1SM", "hbMwzx8",
    "hLBfsoN", "7fqRXUp", "q0NK3je", "ZL0lkpn"
  ],
  "happy":[
    "JwmKLWg", "xvoAhQ1", "4HQQCpF", "bbfsMC3", "0nCCqnu", "zkqutM9",
    "JGipzNn", "4kjCccc", "Gkp9M4T"
  ],
  "holdhands":[
    "fNGDlqB", "3KIDQlu", "dcgGJ9A", "jXqSIgz", "pFvrgo8", "46MuGTr",
    "3if9scl", "1gliMhN", "cRxuZvC", "CnvaxRp", "IUHLuKe", "9J09nvm",
    "AnzriGs", "363rCne", "7kolbuw"
  ],
  "hug":[
    "tvNBTu2", "vFmpgg0", "viVO3di", "wNp3Sxy", "qak7ZRU", "1z6AF8B",
    "skHy0II", "4XI3Z5Q", "OTmRNMZ", "qdlXpQq", "PqzJ9mM", "fq6XGpz",
    "2puJauQ", "D6Nganw", "hkfUbY0", "jcksmvV", "GVs2Ojy", "atvRpzS",
    "QQZLfMp", "w0KUSu0", "VhClqDq", "p4jR1Wo", "PPdJ2io", "QJ8PDKM",
    "UzzYnnW", "doIO3ID", "pRzlYCd", "l9XGYVY", "dzaDGMo", "hTGcauj",
    "qZ7KwmL", "C2xgaxw", "Dp62lUW", "Fp7hTI9", "bN5t2wD", "WrrCrSf",
    "2exhGdR", "t5pujxD", "bZfeFOs", "ZxoV9aM", "D5LfFHl", "p8iTSbo",
    "Fts04VF", "yQdOgTH", "97Qqs4F", "HeYolkI", "Zjz71iI", "os0Fr1n",
    "UFrhKyv", "VyTKXPZ", "93zGXzU", "HvAvAMS", "n01wKIS", "Di71SrF",
    "5TkGdlM", "8T7hGQy", "dljPoHB", "SW8faSL", "GJXdjvL", "2QMRCzk",
    "pvJGgh3", "605Xhe0", "fxbfh4W", "WkfL8i0", "sGmuFX4", "AyW30qe",
    "98VUbvn", "utvYNK9", "ejSVdUw", "eMX1zfy", "TX4wm95", "CQ0UQ7V",
    "SSayTIk", "1ZtJcsH", "kwgUnom", "oF5FfVm", "O1K33kv", "B17moD7",
    "zqSz983", "FrBwFoS", "BMNd9hl", "xo8Mzeq", "CXmRA0I", "SlvL9tO",
    "dtj9yu7", "R60fnwe", "2B6drCO", "i3w4qsg", "FwmVCce", "6P8iW8C",
    "YGY0cWX", "d18fqLj", "o6CTN4v", "yJ5Aeas", "XTkSh88", "dFITAOY",
    "ecFaXuH", "BNl3Iqr", "MLP7juN", "lItx4SU", "IsR2Kdw", "QghzxNa",
    "Z5DpKer", "J9EDW2g", "33GnoBC", "QNNA4M2", "LWhsSJU", "nOuAxhI",
    "qSejAy0", "vFwUm3E", "kif6tPp", "QBlUzrl", "NjUA3dn", "x11OYI1",
    "EVtWJHw", "UcSS0oZ", "HNcRPJ7", "1jZ7TBv", "xRZ7zg1", "ZzYUNjv",
    "OGHfXlE", "KPbKHJ1", "QdETnvv", "rPoxqas", "hcxDeFZ", "la2DSbP",
    "I8LyQ9L", "SOMVzbs", "Y9CAUOl", "IA3SPKQ", "DLemGGB", "w0Phmum",
    "Mi0m04x", "KN2ahrk", "2v3eUQw", "OIPxM9W", "PGi9wI3", "31cOxQo",
    "6rcYdTr", "FLIL0w1", "MnvUsMR", "Y3QbFFo", "vc44IVn", "6JrBbSk",
    "wvY09jh", "kwI7L1A", "yLLtIQ1", "wlJgNTo", "KMJEjiZ", "HG9jg5U"
  ],
  "interesting": [],
  "kick": [
    "3ma4Kfc", "glILp6z", "VcTZyAD", "XS9CrGq", "xsHVHUR", "jxjQScB",
    "gCjNRvM", "jPwRNlA"
  ],
  "kill":[
    "3Rz9rAA", "rzLZGpF", "Qnhg8x1"
  ],
  "kiss": [
    "cQb3Syu", "6X5whF4", "VPX72Yr", "KOwVPHm", "Mb8cuEE", "Sf3PQib",
    "mHQJzCw", "i4GTJis", "jieDYzE", "9Jysw7v", "PFQtiSR", "PtTGWsK",
    "cCDzx3n", "yDCpb4F", "e9FUOIN", "pr3SSyn", "6v3ZupQ", "OKLt0ob",
    "fPIkN6y", "J0vc2we", "hnN5BGs", "9D9s4wu", "K9IUl2C", "UvM4AIV",
    "SBxOe8I", "RTBooo2", "ze5lFGS", "w40o9DC", "bK4OfSr", "bdGETIe",
    "QfpLlm5", "p52FLFw", "nay3j6g", "vlnjhjf", "FmHqHyw", "1wHa9nV",
    "p398V46", "gmIzYat", "XykIxMx", "NJyKrGf", "tsrXJBf", "mBdm4RX",
    "woszJT8", "QvyDstJ", "oLxHAEG", "QDyegD6", "Od9uUel", "3P3z8lW",
    "fCaIOLi", "fAo2Lkp", "XiT3rlA", "ZH2JkVU", "afHAtNB", "ojL0lxj",
    "r4W60W8", "HZfXcTS", "LY4MXJQ", "XMyg3L4", "4ZqKwai", "qh0dzb5",
    "xkRUkxZ", "9gDfPL3", "K4WvdV6", "cesqD94", "3drXUt2", "miaK7Kr",
    "gl0sdL0", "7LpgmHt", "HgsQe98", "NbXKh05", "Qstk37u", "spXoXLc",
    "E04Vz1Z", "x3w1zy5", "DqLe1pQ", "NAEaw6l", "MGmDeXw", "7Vi3k9P",
    "s3eVoVr", "ug7SNvg", "EJ024nF", "oLOpBgD", "W5HpN6U", "jaqenQH",
    "trRcOhj", "F5XzFWp", "bCxByFx", "ZwIMMiz", "RSHnqTf", "jkFdgbz",
    "0yDqnPt", "NVK9HAS", "Ii6KWwW", "opiF9Ua", "aIQJjVr", "JjMyDAS",
    "rGC9n7R", "bATK7GF", "R7A8wby", "eQfa6Ko", "4kQzyI2", "1Nfkm71"
  ],
  "lick":[
    "CHHlRfG", "L5CyK5B", "YzoJv0Y", "WFj5Axk", "4FTR7pU", "tdXIxic",
    "9yHW6ue", "wBYjt9N"
  ],
  "midfing":[
    "xW8aPyL", "56PukJb", "2lTUrGA", "lr0W2He", "PnhwqzZ", "0JlHMlW",
    "qwvkDoR", "bryOtIH", ""
  ],
  "pat": [
    "XFsOKXE", "q34q2p3", "UrtzXZM", "Id0vwI6", "SJHuQgZ", "uYlWOKN",
    "38tuFhI", "IilLHuH", "D2YrdSM", "DVdZh8b", "6gN451Y", "2V4Bn01",
    "Cdu6vMf", "NAuBE65", "9BoPHMG", "A26nqRh", "iG0e32B", "CRRStjK",
    "Gwkc0MQ", "Ne4PPmp", "GNyzGTD", "WOvvLte", "Tb46gAy", "4M5xtkK",
    "25wzYig", "rRFZbfL", "sfNWfGn", "qNrokhu", "XYXUV8X", "mITgeCe",
    "iLOBZ0s", "s6VpZri", "U1ZDRNJ", "OHpoMDC", "jrHMHcc", "iAqjSyF",
    "6BoDX7a", "lPxCezG", "ZiIjr4D", "A2uz9Wz", "n9L7B3G", "vRlMd6H",
    "5qjiecM", "Uz9Zadf", "JMleKSj", "Rs6WlUi", "1enVw0C", "1lvIvOA",
    "EIZUVry", "gGMCUKt", "pKSgMvZ", "yworAIt", "1X1NhJJ", "mjCeIUO",
    "6Nle4Z2", "9J2Ee4r", "6YNqUhp", "2AB3m5R", "e5FeHHE", "ts9zAdm",
    "fMMXYhB", "7TVDKmU", "UtJWtEn", "erfoIMI", "9tJ8fXJ", "8SJp0KQ",
    "44qSFSc", "xPCnrzY"
  ],
  "poke": [
    "iiaMtNa", "7ZUnnAZ", "DyqJ9ok", "P4R9VGb", "BzjmMa1", "ft8qbXn",
    "JyPFwcy", "clSVlOo", "Z2a6QPZ", "QwXMRTY", "nLSrf3P", "HzXTeo9",
    "rjWbHkG", "rlNvRXy", "E7JBAAC", "zUdYbxX", "CjI5ZlO", "P0ZunBb",
    "5DyDruQ", "Bjdr1po", "jRLYoyR", "FGZXxHH", "qW7AQsD"
  ],
  "slap": [
    "cWeYE1F", "VL0XlR9", "usu5ioL", "mJwnGrF", "ncIyZ63", "Lyi2rhK",
    "xAFPVC7", "2BJIDZr", "XhmnueL", "zQ6y1Oz", "UFtUfov", "8reDxXO",
    "JgXas5t", "1Gvoguw", "dr3xQvW", "1eRiC4c"
  ],
  "sleep":[
    "NsLqS9d", "r5Lrhnt", "3YFSqTk", "LOpUSQP", "YyVDiVX", "ZDPukql",
    "fjdHCdB", "j6MIz6Z", "jgI66b6", "ZDfWFwA", "vavcmrv", "yviMY0r",
    "FDuRl2k", "UsIPKAw", "XXuxIJP", "rAvADgY", "FqL4fde", "t8YSWon",
    "noahhz7", "DxqNaN1", "z6DjK4I", "ANRw0ya", "67Fyhwf", "MP5DPPN",
    "SmHuNbA", "vIPnHtc", "36EGBCJ", "tctzjPV", "gnYyKDB", "XylgXah",
    "hGabYAk", "56gW65P", "SNqgfWY"
  ],
  "smile":[
    "HnNBPfP", "0HmEBV2", "pxEaH3n", "d0hN3Pf", "ceQRPHE", "sfswypY",
    "0ZsREe8", "h0NRqOR", "xd4V7Wo", "FzihIxv", "GwUn6Eu", "ako9fPf",
    "5VNAuAN", "iVvFegH", "MrM9tei", "m5U2COT", "C1AOj2v", "dQ1pYsr",
    "a2OFjWe", "XZbvFZe", "mVrMgk5", "YBxd6gi", "pCQnSPt", "ExGT9kI",
    "Ebt5WUz", "0yqpMXL", "HGAhAW1", "8xCIqUA", "iuBGUSi", "XNep1Eb",
    "eyaOyE0", "f8GnxzS", "X1e9LfO", "rvvalVd", "oTCJEoI", "Nu3JLoW"
  ],
  "smug": [
    "n3gxIKM", "kKsgxSo", "cJlVdVQ", "JiI9zNR", "lvmorNN", "hnRqttQ",
    "0ztmxKQ", "Cbmf4mA", "u7QEzHS", "R1MPUr2", "zMrapUE", "iUebBwc",
    "JcgkZ3l", "E5i5Ap7", "eYZ7nwa", "9wd72N6", "IEv7jLO", "F3ocWjE",
    "UFl89kx", "GT005OK", "N9k8ojy", "LmTX03p", "MVVMYbe", "mu21WsM",
    "hN2B2Ts", "f8PZpMd", "AlqEv5g", "lYwZGKU", "IM25W16", "THl44Uy",
    "vStghVm", "2oaNDjZ", "HJa7SGJ", "LiG0DoB", "tJlo6L3", "KSRlwVi",
    "alck9lZ", "65vUwBF", "FwzBNZJ", "HioOyiX", "IJPjurj", "D2BFLql",
    "K0qoINk", "vNN7gh4", "yRV9ow0", "iLoyfPp", "UQ7WJvd", "DmLEHhW",
    "rLFhzeG", "0Tcmt0W", "5pggzZ1", "ikNakym"
  ],
  "suicide":[
    "uPOgWEL", "pXQ3Tbu", "qeJMJYL", "lDl7kfX", "5WTXS5L", "iH4xt67",
    "RVbPHuL"
  ],
  "tickle": [
    "cKv6wJi", "xTCXQ9K", "8ZEjA9C", "BNkCALK", "6ltZTlv", "8lt4QU8",
    "gfu2VBV", "WQFBtb6", "2oEN7SF", "8AFOrgf", "CqylXCq", "X6wGn3y",
    "C4MmaER", "171EHxa", "ILfm1EP", "bKcgwHW", "nmYqS8l", "IcAP19n",
    "pENMORd"
  ],
  "wave":[
    "Rvh9LTm", "pUL03sH", "EvevOAv", "OuRyd1y", "91chler", "HJBZ3Z9",
    "SeFfIDk", "vPjgKw5", "62bDTPI", "jhTf7CG", "PGalAXV", "ctHE7dU",
    "bOOETQR", "u3fTy63", "IPEBJfU", "lKB4JYj", "0FBKsjp", "uacqjGS",
    "332DOvG", "FcHzylB", "gLMueWE", "qZLsZMq", "yzS7s6g"
  ],
  "wink":[
    "6zW1gTg", "peTeUuV", "mdaUExv", "MB8x4yO", "MxEuxWz", "6MW9thg",
    "2bfXlQG", "M0rIIUC", "IryKFc6", "7ZcfU0c", "yiUCEEq", "nwzp30i",
    "QDMeQsd", "rP0HbsB", "1Jompuw", "Aiemomr", "stFAght", "ruZ8pKk",
    "VuN7wXo", "4FgPRMK"
  ]
}

**Comment by BearTS** [comment]
will be reopening this pr on master with the latest commits to avoid conflict 👍

**Comment by BearTS** [comment]
nvm i can merge the commits to this patch and do changes

**Pull request closed without merging**
