### PR TITLE
Music System For Mai

### PR DESCRIPTION
**Pull request by BearTS**
Music System For Mai Bot

### CODE REVIEW

**Comment by maisans-maid** [comment]
image

**Comment by maisans-maid** [comment]
I've decided. Let's pull this on v3.1.0 of the bot.

**Comment by maisans-maid** [comment]
There's no v3.1.0. Didn't expect myself to force it to v4 tho. Hmmm, let's check it again if it does not cause any errors when merged with v4

**Comment by BearTS** [comment]
will be making a pr on mai v4

**Pull request closed without merging**
