### PR TITLE
Hindi

### PR DESCRIPTION
**Pull request by BearTS**
40% done

### CODE REVIEW

**Comment by maisans-maid** [comment]
hows the progress for this one? just checking up.

**Comment by BearTS** [comment]
haulted for the while since exams, i will try to finish it asap

**Comment by BearTS** [comment]
Can Merge

**Comment by maisans-maid** [comment]
This broke the bot, you didn't validate the JSON lmao

**Comment by maisans-maid** [comment]
Fixed on [e3fa008](https://github.com/maisans-maid/Mai/commit/e3fa00810ca6a169413dbe4e9d4b2f7b86a7c55e)

**Pull request merged**
