### PR TITLE
Minor update to get ready for web

### PR DESCRIPTION
**Pull request by conqr2**

### CODE REVIEW

**Comment by Slowlife01** [comment]
What even is this for, so you never used it and just leave it there 👀

**Comment by conqr2** [comment]
> What even is this for, so you never used it and just leave it there 👀
We're getting ready for something big, that's just the code that imports it so that the bot can remain open source and working

**Comment by conqr2** [comment]
Who are you, and when did I ask you for your opinion on this?

**Comment by kakarot-dev** [comment]
Thats rude

**Comment by kyoyacchi** [comment]
Bruh moment

**Comment by kakarot-dev** [comment]
lol just kidding

**Comment by conqr2** [comment]
moved to org

**Pull request closed without merging**
