### PR TITLE
(added) Update message.js to receive DMs

### PR DESCRIPTION
**Pull request by Manzanitabot123**
Although this function is not correct, I hope that one day they will implement it.
It consists of receiving direct messages in a text channel sent to the bot.

### CODE REVIEW

**Comment by kakarot-dev** [comment]
This is equal to spamming the api and ruining the privacy of thr author

**Comment by kakarot-dev** [comment]
I disagree with this

**Comment by Manzanitabot123** [comment]
You're absolutely right, it was just an idea, an apology

**Comment by kakarot-dev** [comment]
no problemo!

**Pull request closed without merging**
