### PR TITLE
Add Market Enteries

### PR DESCRIPTION
**Pull request by BearTS**
Addition of more Emblems

### CODE REVIEW

**Comment by BearTS** [comment]
Dimensions of Emblems is 200x200

**Review by maisans-maid — CHANGES_REQUESTED** [review]
The link are just the same, and also pls limit the emblem to 1 emblem per character.

**Review by maisans-maid — APPROVED** [review]

**Comment by maisans-maid** [comment]
This is in reference to pull (#33). Please use this reference onwards

**Comment by BearTS** [comment]
hmm alrighty :D

**Pull request merged**
