### PR TITLE
Added osu, anime fact commands

### PR DESCRIPTION
**Pull request by NotKyoyo**
osu! command requires authorization, so you can get the token from [here](https://osu.ppy.sh/p/api)

### CODE REVIEW

**Comment by maisans-maid** [comment]
Wait cause i'd have to take a look on the new dependencies you've added here.

**Comment by NotKyoyo** [comment]
Sure, take your time!

**Comment by maisans-maid** [comment]
Will add this on the next overhaul

**Comment by maisans-maid** [comment]
Added and modified on overhaul. Expect this feature in v5 <3

**Pull request closed without merging**
