### PR TITLE
Adding more items to market

### PR DESCRIPTION
**Pull request by BearTS**
👍

### CODE REVIEW

**Comment by BearTS** [comment]
cropped the images and set their dimensions to 475*250 so it wont take time or display wrong aspect ratio of the images

**Comment by maisans-maid** [comment]
aaaaa. too much tamako that it outnumbered mai's entries on the market. Wait a min, i'll select some.

and ps. as i said before, you may not insert the new items in the middle of the json file cause it messes up with the other ids, items in the database are stored as ids, and once the bot gets them, they may return the wrong item based on the id.

**Comment by BearTS** [comment]
oopsie my bad ;-;. Will keep that in mind + i will send you a imgur album to choose from

**Comment by maisans-maid** [comment]
ok thanks, that would be helpful. Please don't delete entries that will be left out cause I may use some of them in the future.

**Comment by maisans-maid** [comment]
please don't delete the branch yet, i'll just add on this branch aswell before merging to v4

**Pull request merged**
