### PR TITLE
Addition of more Patterns

### PR DESCRIPTION
**Pull request by BearTS**

### CODE REVIEW

**Comment by maisans-maid** [comment]
You don't have to insert item documents to the json file, just add them by incrementing ids :)

**Comment by maisans-maid** [comment]
also, if possible, please downscale the images to 300x600 exact resolution (for patterns only). Large resolutions will take time for canvas to process and mismatched resolutions will cause the image to stretch. Sanks 👍

**Comment by BearTS** [comment]
> also, if possible, please downscale the images to 300x600 exact resolution (for patterns only). Large resolutions will take time for canvas to process and mismatched resolutions will cause the image to stretch. Sanks 👍

will do that soon once i finish a feature request with my bot 👍

**Comment by maisans-maid** [comment]
Pattern price ranges from 12500-20000 depending on rarity too. If possible, attach the prices, and since it's the one you submitted, you may decide

**Comment by maisans-maid** [comment]
Included on [this pr](https://github.com/maisans-maid/Mai/commit/1a1ccc9e82a6c716c251cff812d8b08eb2e0ad03) (check line 453)

**Pull request closed without merging**
